STEP-2 Add Functionality to Add Tasks
iud-wtag/Todos pull request #2
Opened 2023-03-02 04:25 UTC by iud-wtag

[STEP-2](https://trello.com/c/7M0DaC4B)
This PR introduces the functionality of add task and showing the barebone format of task board.

## Types of Changes
* Added input field according to Design
* Connected Store with Redux
* Added Task and showing them in barebone format with some basic styling.

## Review
Please have a close look on this PR and kindly put you valuable comments.

https://user-images.githubusercontent.com/124483067/224528763-e9709d88-79ee-417f-b414-461b871e563a.mov

2023-03-02 07:01 UTC, fza-wtag requested changes
Summary of the review:

- [ ] Try to avoid writing codes that are not necessary for the current step.
- [ ] Try to create separate components for different parts.
- [ ] Try to use descriptive variable names to make them more understandable.
- [ ] Try to keep your application state in the Redux store to benefit in the long run.

Other than that, so far good initial work 🚀👏

2023-03-05 07:35 UTC, iud-wtag commented on src/reducers/todoReducers.js
>        };
isn't using sorting building up time complexity?
how about taking the format like that?
![Screenshot 2023-03-05 at 1 35 00 PM](https://user-images.githubusercontent.com/124483067/222947966-7b376dbe-0aa5-49d6-a459-065f021c4ac9.png)

2023-03-05 10:31 UTC, fza-wtag commented on src/reducers/todoReducers.js
>        };
Good point. That will also fulfill our requirements. 👌

2023-03-05 10:41 UTC, fza-wtag requested changes
++ Adding a cursor focus pointer to the input field and getting the Add Task job done with the Enter key of the keyboard may increase the user experience.

2023-03-05 10:41 UTC, fza-wtag commented on src/components/Todo/TodoViews/TodoViews.jsx
> +      })
Please try to create a separate component for this part and use that instead by passing the necessary props.

2023-03-05 10:41 UTC, fza-wtag commented on src/components/Todo/TopBar/TopBar.jsx
> +}
Reason behind doing so?

2023-03-05 10:41 UTC, fza-wtag commented on src/components/Todo/TopBar/controllers/FilterTodo.jsx
> +// FilterTodo.propTypes = {}
Remove this line if not needed.

2023-03-05 10:42 UTC, sai-wtag commented on package.json
>    },
Best practice to provide engines
```suggestion
  },
  "engines": {
    "node": "16.x",
    "npm": "8.19.x",
    "yarn": "1.22.x"
  },
```

2023-03-05 10:43 UTC, sai-wtag commented on src/components/Todo/TodoViews/TodoViews.jsx
> +const TodoViews = ({todoList,}) => {
remove the comma

2023-03-05 10:44 UTC, sai-wtag commented on src/components/Todo/TopBar/controllers/FilterTodo.jsx
> +// import PropTypes from 'prop-types';
Remove unnecessary comments

2023-03-05 10:44 UTC, sai-wtag commented on src/components/Todo/TopBar/controllers/FilterTodo.jsx
> +// FilterTodo.propTypes = {}
ditto

2023-03-05 10:56 UTC, sai-wtag commented
It would be nicer if you make the 'delete' action for only add task component.

![Screenshot 2023-03-05 at 4 53 38 PM](https://user-images.githubusercontent.com/122719191/222956188-943350b8-5479-42d6-8d6b-447ea4969618.png)

2023-03-05 10:56 UTC, sai-wtag approved these changes
Locally tested. LGTM Approved with some changes. Thanks

2023-03-06 04:15 UTC, iud-wtag commented on package.json
>    },
Added That.. Thanks

2023-03-06 04:16 UTC, iud-wtag commented on src/components/Todo/TodoViews/TodoViews.jsx
> +const TodoViews = ({todoList,}) => {
resolved

2023-03-06 05:05 UTC, iud-wtag commented on src/components/Todo/TopBar/TopBar.jsx
> +}
isn't it the best practice to passing props with required in every layer so that no data is missing?

2023-03-06 07:48 UTC, iud-wtag commented
> It would be nicer if you make the 'delete' action for only add task component.
> 
> ![Screenshot 2023-03-05 at 4 53 38 PM](https://user-images.githubusercontent.com/122719191/222956188-943350b8-5479-42d6-8d6b-447ea4969618.png)

This feature will add in Step-3-delete-task branch. Thanks for mentioning.

2023-03-06 09:57 UTC, fza-wtag requested changes
++ The Add Task Card loaded up with an extra new line. Please take care of it.
![image](https://user-images.githubusercontent.com/119289799/223076849-72744033-df01-4e14-a492-6622ca0a8046.png)

++ Highly recommending `prettier` as the default formatter.

2023-03-06 09:57 UTC, fza-wtag commented on src/components/Todo/Todo.jsx
> +          )}
```suggestion
         {isCreateBtnClicked && 
            <AddCard
              handleInputChange={handleInputChange}
              handleAddTask={handleAddTask}
              inputData={inputData}
            />
          }
```

2023-03-06 09:57 UTC, fza-wtag commented on src/components/Todo/TodoViews/TodoViews.jsx
> +          <p className='todo-createTime'>Created At: {list.time}</p>
Can we move this part into another new Component?

2023-03-06 09:57 UTC, fza-wtag commented on src/components/Todo/TodoViews/controllers/IncompleteTask.jsx
> +      <button><img src="assets/images/delete.png" alt="Delete Btn" /></button>
```suggestion
      <button><img src="assets/images/check.png" alt="Complete button" /></button>
      <button><img src="assets/images/edit.png" alt="Edit button" /></button>
      <button><img src="assets/images/delete.png" alt="Delete button" /></button>
```

2023-03-06 09:57 UTC, fza-wtag commented on src/components/Todo/TopBar/controllers/CreateTodo.jsx
> +        <img src="assets/images/plus.png" alt="plus" />
```suggestion
        <img src="assets/images/plus.png" alt="Create icon" />
```

2023-03-07 09:42 UTC, fza-wtag approved these changes

2023-03-07 09:42 UTC, fza-wtag commented on src/actions/index.js
> +      time: new Date().toLocaleDateString("de-DE"),
```suggestion
      date: new Date().toLocaleDateString("de-DE"),
```

2023-03-07 09:42 UTC, fza-wtag commented on src/components/Todo/TodoViews/views/TodoDetails.jsx
> +      <p className="todo-createTime">Created At: {list.time}</p>
ditto

2023-03-07 09:42 UTC, fza-wtag commented on src/reducers/todoReducers.js
> +      const { id, data, time } = action.payload;
ditto

2023-03-07 09:42 UTC, fza-wtag commented on src/reducers/todoReducers.js
> +            time: time,
ditto

2023-03-07 09:42 UTC, fza-wtag commented on src/components/App.jsx
>        <div>
Unnecessary div. We can remove this

2023-03-07 09:42 UTC, fza-wtag commented on src/components/Navbar/controllers/SearchBar.jsx
> +    <div>
We may also remove this div if this is not needed right now as we haven't added the search input field yet.

2023-03-08 11:06 UTC, ana-wtag approved these changes

2023-03-09 11:17 UTC, fza-wtag approved these changes

2023-03-12 04:48 UTC, iud-wtag commented on src/components/Todo/Topbar/filter-todo.component.jsx
> +const FilterTodo = (props) => {
removed that.. thanks

2023-03-12 04:49 UTC, iud-wtag commented on src/actions/index.js
> +import * as actionTypes from "actions/actionTypes";
updated. thanks

2023-03-12 04:51 UTC, iud-wtag commented on src/components/Todo/todo.jsx
> +      setInputData("");
in terms of input data null value is raising an error. I think Empty string suites the meaning here.

2023-03-12 04:57 UTC, fza-wtag commented on src/components/Todo/todo.jsx
> +      setInputData("");
What kind of error? Can you please elaborate? And isn't it better to have a `null` instead of an empty string regarding memory usage?

2023-03-12 05:02 UTC, iud-wtag commented on src/components/Todo/todo.jsx
> +      setInputData("");
This kind of errors occurs, cause i'm sending the value as props to the child component which required not to be null. Thanks.

![Screenshot 2023-03-12 at 11 01 00 AM](https://user-images.githubusercontent.com/124483067/224525354-54b88aa7-9ac3-49b9-afca-5da6be9fa9c7.png)

2023-03-12 08:38 UTC, ana-wtag approved these changes

2023-03-12 08:39 UTC, sta-wtag approved these changes
LGTM

2023-03-12 09:09 UTC, hhu-wtag requested changes

2023-03-12 09:09 UTC, hhu-wtag commented on src/components/Todo/AddCard/add-card.jsx
> +import FormButtons from "components/Todo/AddCard/form-buttons.component";
Any particular reason for this naming convention?

2023-03-12 09:09 UTC, hhu-wtag commented on src/components/Todo/todo.jsx
> +    (state) => state.handleTokens.isCreateBtnClicked
What is `handleTokens` here?

2023-03-12 09:09 UTC, hhu-wtag commented on src/components/Todo/todo.jsx
> +  };
Can we make this a global helper and use it where needed?

2023-03-12 09:09 UTC, hhu-wtag commented on src/components/Todo/todo.jsx
> +    }
```suggestion
    if (sanitizedData.trim() === "") {
      toggleEmptyError()
      return
    } 
    dispatch(addTodo(sanitizedData));
    setInputData("");
    handleCreateClick()
```

2023-03-12 09:09 UTC, hhu-wtag commented on src/components/Todo/todo.jsx
> +    if (e.key === "Enter") {
Can we use a const here?
```suggestion
    if (e.key === ENTER) {
```

2023-03-12 09:09 UTC, hhu-wtag commented on src/reducers/handleTokens.js
> +const handleTokens = (state = initialToken, action) => {
What are "tokens"? If they are equivalent to "tasks" then can we name them "tasks"?

2023-03-12 09:21 UTC, iud-wtag commented on src/components/Todo/AddCard/add-card.jsx
> +import FormButtons from "components/Todo/AddCard/form-buttons.component";
In general case react component use PascalCase naming convention. So for this, here I use `FormButtons` in pascalCase.

2023-03-12 10:12 UTC, iud-wtag commented on src/components/Todo/todo.jsx
> +    (state) => state.handleTokens.isCreateBtnClicked
here `handleTokens` is redux state for handling the create button clicked or not..

2023-03-12 11:25 UTC, iud-wtag commented on src/components/Todo/todo.jsx
> +    }
Done that vaia.. Thanks

2023-03-12 11:26 UTC, iud-wtag commented on src/components/Todo/todo.jsx
> +    if (e.key === "Enter") {
vaia `e.key===ENTER` is raising error. e.key has the property `"Enter"`

2023-03-12 11:29 UTC, iud-wtag commented on src/components/Todo/todo.jsx
> +  };
Done that vaia.. Thanks.

2023-03-12 11:30 UTC, iud-wtag commented on src/components/Todo/todo.jsx
> +    (state) => state.handleTokens.isCreateBtnClicked
Changed the `handleTokens` to `handleButtonClick`. Thanks

2023-03-12 11:31 UTC, iud-wtag commented on src/reducers/handleTokens.js
> +const handleTokens = (state = initialToken, action) => {
Changed the `handleTokens` to `handleButtonClick`. Thanks

2023-03-12 12:01 UTC, hhu-wtag commented on src/components/Todo/AddCard/add-card.jsx
> +import FormButtons from "components/Todo/AddCard/form-buttons.component";
But the actual component name doesn't follow the PascalCase here.

2023-03-12 12:11 UTC, hhu-wtag approved these changes

2023-03-13 09:21 UTC, ray-wtag commented on jsconfig.json
> +}
Use prettier please

2023-03-13 09:21 UTC, ray-wtag commented on package.json
> +    "yarn": "1.22.x"
as you are using yarn, i don't think there would be any package.lock file, instead there should be yarn.lock

2023-03-13 09:21 UTC, ray-wtag commented on src/components/Todo/Topbar/filter-todo.component.jsx
> +      <button className="btn">All</button>
ditto

2023-03-13 09:21 UTC, ray-wtag commented on src/components/Todo/Topbar/filter-todo.component.jsx
> +      <button className="btn">Incomplete</button>
ditto

2023-03-13 09:21 UTC, ray-wtag commented on src/components/Todo/Topbar/filter-todo.component.jsx
> +      <button className="btn">Complete</button>
ditto

2023-03-13 09:21 UTC, ray-wtag commented on src/components/Todo/Topbar/top-bar.jsx
> +      <h1 className="addTask-header">Add Task</h1>
no camelcase in classname

2023-03-15 12:41 UTC, iud-wtag commented on jsconfig.json
> +}
Vaia I have already used prettier in my project.. can you specify more about that?

2023-03-22 05:02 UTC, ray-wtag approved these changes

2023-03-27 03:34 UTC, cho-wtag commented on src/assets/css/style.css
> +@import url("https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap");
Please follow code indentation!

2023-03-27 03:35 UTC, cho-wtag commented on src/assets/css/style.css
> +  max-width: 1216px;
instead of `px` please use `rem` unit

2023-03-27 03:37 UTC, cho-wtag commented on src/assets/css/style.css
> +  background: #ffffff;
It is a good practice to maintain a color variables file where all colors can be included.

2023-03-27 03:39 UTC, cho-wtag commented on src/assets/css/style.css
> +.todo-view__btns > button {
Rather, directly using tag names in a CSS file please introduce a specific class name.

2023-03-27 06:54 UTC, iud-wtag commented on src/assets/css/style.css
> +@import url("https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap");
resolved

2023-03-27 06:55 UTC, iud-wtag commented on src/assets/css/style.css
> +  max-width: 1216px;
updated with rem unit

2023-03-27 06:55 UTC, iud-wtag commented on src/assets/css/style.css
> +  background: #ffffff;
includes color variables file.

2023-03-27 06:56 UTC, iud-wtag commented on src/assets/css/style.css
> +.todo-view__btns > button {
This was left mistakenly. updated. Thanks apu.

2023-03-28 02:42 UTC, cho-wtag commented on src/assets/css/style.css
> +  padding: 1.875rem 0px;
`1.875rem 0px` ?

2023-03-28 02:42 UTC, cho-wtag commented on src/assets/css/style.css
> +  border: 1px solid var(--border);
ditto

2023-04-04 05:58 UTC, hhu-wtag approved these changes

2023-04-04 05:58 UTC, hhu-wtag commented on src/actions/index.js
> +      date: new Date().toLocaleDateString("de-DE"),
Why german?

2023-04-04 05:58 UTC, hhu-wtag commented on src/components/Todo/AddCard/add-card.jsx
> +      <AddActionBar
```suggestion
      <ActionBar
```

2023-04-04 06:29 UTC, iud-wtag commented on src/actions/index.js
> +      date: new Date().toLocaleDateString("de-DE"),
There isn't any special case bhai, but found out that the format of the date matches with german format.
![Screenshot 2023-04-04 at 12 17 26 PM](https://user-images.githubusercontent.com/124483067/229704550-b09dc731-872d-4080-bf91-0155675c52ff.png)

NB: another way found that also matches the format. but found that little bit complex. So use the previous one.

> const today = new Date();
const day = today.getDate();
const month = today.getMonth() + 1; // Note: January is 0
const year = today.getFullYear();
const formattedDate = \`${day}.${month}.${year}`\;

Bhaia, should i use that?

2023-04-04 06:36 UTC, iud-wtag commented on src/components/Todo/AddCard/add-card.jsx
> +      <AddActionBar
Later on i also have `ViewActionBar` for ViewCard and `EditActionBar` for EditCard. so can i use `AddCardActionBar` in this to specify it for AddCard? Thanks

2023-04-04 06:40 UTC, hhu-wtag commented on src/actions/index.js
> +      date: new Date().toLocaleDateString("de-DE"),
Yes obviously. Using the german locale will lead to unexpected bug in the future.

2023-04-04 06:43 UTC, hhu-wtag commented on src/components/Todo/AddCard/add-card.jsx
> +      <AddActionBar
I'm not sure about having different action bar for different goal. We can have on component named `<ActionBar />` and we can send prop named `mode` to set the mode of the action bar. Depending on the mode, e.g: edit mode, will change the component to edit mode and so on.

2023-04-04 07:38 UTC, iud-wtag commented on src/actions/index.js
> +      date: new Date().toLocaleDateString("de-DE"),
resolved

2023-04-04 13:16 UTC, cho-wtag approved these changes

2023-04-05 05:31 UTC, iud-wtag commented on src/components/Todo/AddCard/add-card.jsx
> +      <AddActionBar
As we discussed, keeping the `AddCardActionBar` separated because of different functionality and merging the components of `EditActionBar` and `ViewActionBar` together as `ActionBar`. Thanks!

2023-04-17 05:34 UTC, ray-wtag commented on src/assets/css/style.scss
> +.navbar__container {
```suggestion
.todo , .navbar {
&__container {
```

2023-04-17 05:34 UTC, ray-wtag commented on src/assets/css/style.scss
> +.todo__section {
```suggestion
.todo{
&__section {
```

2023-04-17 05:34 UTC, ray-wtag commented on src/assets/css/style.scss
> +.todo-logo__txt {
ditto

2023-04-17 05:34 UTC, ray-wtag commented on src/assets/css/style.scss
> +.navbar-back__navbar {
ditto

2023-04-17 05:34 UTC, ray-wtag commented on src/assets/css/style.scss
> +.todo-top__btn-section {
ditto

2023-04-17 05:34 UTC, ray-wtag commented on src/assets/css/style.scss
> +.create-btn__btn {
please fix the format in all over the css file

2023-04-17 05:34 UTC, ray-wtag commented on src/components/Todo/Navbar/navbar.jsx
> +    <div className="navbar-back">
```suggestion
    <div className="navbar__wrapper">
```

2023-04-17 05:34 UTC, ray-wtag commented on src/components/Todo/Topbar/create-todo.component.jsx
> +        className="create-btn__btn btn purple-back__btn"
please change the classnames with suitable names

2023-05-02 03:16 UTC, bia-wtag approved these changes

2023-06-19 13:34 UTC, merged