Step-3 Add functionality to Delete tasks
iud-wtag/Todos pull request #3
Opened 2023-03-06 13:13 UTC by iud-wtag

[STEP-3](https://trello.com/c/kEGtbEtF)
This PR introduces the functionality of delete task and updating the format of task board.

## Types of Changes
* Cancel button implemented in create card menu.
* Delete task from store when clicked on the delete button.
* UI updated when task is deleted.

## Review
Please have a close look on this PR and kindly put you valuable comments.

https://user-images.githubusercontent.com/124483067/223119402-521773a5-262f-4b2f-8972-4e81f4f0bf7d.mov

2023-03-07 09:09 UTC, sai-wtag approved these changes
Locally tested. LGTM. Thanks

2023-03-07 10:08 UTC, fza-wtag requested changes
Try to format your codes always to maintain a cleaner look. You can also configure your formatter (Prettier) to automatically format the code whenever the file is changed. Read more [here](https://www.alphr.com/use-prettier-vs-code/#:~:text=your%20CSS%20files.-,Automatically%20Format%20Document%20on%20VS%20Code%20Using%20Prettier,-Open%20the%20VS).
Other than that Good work so far. 🚀

2023-03-07 10:08 UTC, fza-wtag commented on src/components/Todo/TodoViews/controllers/IncompleteTask.jsx
> +        }}
Can we separate this into another function on top?

2023-03-08 06:58 UTC, iud-wtag commented on src/components/Todo/TodoViews/controllers/IncompleteTask.jsx
> +        }}
as a callback instead of separate component can we declare those function as this?
`onClick={() => handleDeleteTask(taskID)}`

2023-03-08 07:04 UTC, fza-wtag commented on src/components/Todo/TodoViews/controllers/IncompleteTask.jsx
> +        }}
Not component separation. Was asking to keep the onClick clean with only one variable and define that variable as an arrow function on the same component scope right above the return. Got my point now?

2023-03-08 11:08 UTC, ana-wtag approved these changes

2023-03-09 03:51 UTC, fza-wtag approved these changes
Also tested locally, LGTM. ✅

2023-03-12 08:40 UTC, sta-wtag approved these changes
LGTM

2023-03-13 09:24 UTC, ray-wtag approved these changes

2023-03-21 06:12 UTC, hhu-wtag approved these changes

2023-04-04 06:05 UTC, hhu-wtag approved these changes

2023-04-12 08:30 UTC, ray-wtag approved these changes

2023-04-20 06:07 UTC, sam-wtag commented on src/actions/index.js
> +    id,
see https://redux.js.org/tutorials/essentials/part-4-using-data#preparing-action-payloads

```suggestion
    payload: { id },
```

2023-04-20 06:08 UTC, sam-wtag commented on src/components/Todo/AddCard/add-card-action-bar.component.jsx
> +  handleCancelClick,
callback props should be prefixed with `on`

```suggestion
  inputTask,
  isEmptyError,
  onAddTask,
  onCancelClick,
```

2023-04-20 06:09 UTC, sam-wtag commented on src/components/Todo/AddCard/add-card.jsx
> +  handleAddTask,
see https://github.com/iud-wtag/Todos/pull/3/files#r1172120015

2023-04-20 06:09 UTC, sam-wtag commented on src/components/Todo/TodoCards/todo-action-bar.component.jsx
> +const TodoActionBar = ({ handleDeleteTask, todo }) => {
see https://github.com/iud-wtag/Todos/pull/3/files#r1172120015

2023-04-20 06:09 UTC, sam-wtag commented on src/components/Todo/TodoCards/todo-action-bar.component.jsx
> +      <button onClick={() => handleDeleteTask(id)}>
see https://github.com/azo-wtag/todo-app-react/pull/4/files#r1172070329

2023-04-20 06:10 UTC, sam-wtag commented on src/components/Todo/TodoCards/todo-cards.jsx
> +const TodoCards = ({ todoList, handleDeleteTask }) => {
see https://github.com/iud-wtag/Todos/pull/3/files#r1172120015

2023-04-20 06:11 UTC, sam-wtag commented on src/components/Todo/todo.jsx
> +  const handleCancelClick = () => {
see https://github.com/azo-wtag/todo-app-react/pull/4/files#r1172078490

```suggestion
  function handleCancelClick() {
```

2023-04-20 06:12 UTC, sam-wtag commented on src/components/Todo/todo.jsx
> +  const handleDeleteTask = (taskId) => {
see https://github.com/azo-wtag/todo-app-react/pull/4/files#r1172078490

2023-05-02 03:17 UTC, bia-wtag approved these changes

2023-05-02 07:12 UTC, sam-wtag commented on src/components/Todo/TodoCards/todo-action-bar.component.jsx
> +  }
consider inlining the variable, if it is not being reused or the object properties are not being accessed multiple times.

2023-05-02 07:28 UTC, sam-wtag commented on src/components/Todo/todo.jsx
> +  function handleDeleteTask(taskId) {
argument `taskId` would be undefined since it is not being passed when binding the event.

2023-05-02 07:28 UTC, sam-wtag commented on src/components/Todo/todo.jsx
> +            <TodoCards todoList={todoList} onDeleteTask={handleDeleteTask} />
see https://github.com/iud-wtag/Todos/pull/3/files#r1182184821

2023-05-02 07:34 UTC, sam-wtag approved these changes
LGTM 🚀

2023-06-19 13:34 UTC, merged